fixtures:
  symlinks:
    nut: "#{source_dir}"
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref: "6.0.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "7.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.6.0"
